DevjamProject/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from user import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Post.urls')),
    path('register/',user_views.register, name = 'register'),
    path('login/',auth_views.LoginView.as_view(template_name = 'users/login page.html'), name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = 'logout'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name = 'users/pass_forget.html'),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name = 'users/pass_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name = 'users/pass_reset.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/pass_done.html'),name='password_reset_complete'),
    path('user/',include('user.urls')),
    path('group/',include('Group.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Group/urls.py
from django.urls import path
from . import views
from user import views as u_views
from Post import views as p_views

urlpatterns=[
    path('create/',views.CreateGroup.as_view(),name='create_group'),
    path('info/<slug:slug>/<activechannel>/',views.SingleGroup,name='group-detail'),
    path('add-member/<slug:slug>/',views.addmember,name='addmember'),
    path('accept/<slug:userd>/<slug:slug>',views.accept,name='accept'),
    path('reject/<slug:userd>/<slug:slug>',views.reject,name='reject'),
    path('promote_demote/$',views.promote_demote, name = 'promote_demote'),
    path('createpost/<slug:slug>/<channel>/', p_views.GroupPostCreateView, name = "group-post-create"),
    path('createpoll/<slug:slug>/<channel>/', p_views.GroupPollNew, name = "group-poll-create"),
    # path('createpoll/<slug:slug>/<channel>/', p_views.GroupPollCreateView, name = "group-poll-create"),
    path('group-list/',views.ListGroups.as_view(),name='group-list'),
]

Post/urls.py
from django.urls import path
from . import views
from user import views as u_views
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, Search
# , CommentCreateView
from .views import commentFunc
urlpatterns = [
    path('', PostListView, name='blog-home'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('post/<int:pk>/comment/new/', commentFunc, name='post-comment'),
    path('like/$', views.likepost, name = 'like-post'),
    path('<tag>/explore/', views.ExploreTagView, name = 'explore-tag'),
    path('poll/create/',views.pollnew,name='poll_create'),
    path('poll/add/<int:pk>/<int:pollid>/',views.addpoll,name='addpoll'),
    path('search/', Search, name='search'),
]

Group/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.urls import reverse
import misaka
from Tag.models import Tag
# Create your models here.

class Group(models.Model):
    title = models.CharField(max_length=100,unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description =  models.TextField()
    link = models.URLField(blank=True,unique=False)
    members = models.ManyToManyField(User,through="GroupMember")
    tags =models.ManyToManyField(Tag, related_name='group_tag' , blank = True)
    logo = models.ImageField(default='group_default.jpg', upload_to='group_logo')
    created_by = models.ForeignKey(User, related_name = "group_creator",on_delete = models.CASCADE, default = None, null = True)

    def get_absolute_url(self,**kwargs):
        return reverse('group-detail', kwargs={'slug':self.slug, 'activechannel' : "General"})

    def get_channel_url(self,channel,**kwargs):
        return reverse('group-detail', kwargs={'slug':self.slug, 'activechannel' : channel})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        # self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)
        if(not GroupMember.objects.filter(group = self, user = self.created_by).exists()): #creating created by user President
            GroupMember.objects.create(group = self, user = self.created_by, auth = 0, status = 1)
            c = Channel.objects.create(parentgroup = self, name = "General")               #creating groupchannel General
            d = Channel.objects.create(parentgroup = self, name = "Announcements")         #creating groupchannel Announcements upon creating of group
            c.save()
            d.save()

    def __str__(self):
        return self.title

#channel model
class Channel(models.Model):
    parentgroup = models.ForeignKey(Group, related_name = "parent_group", on_delete = models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.parentgroup.title}.{self.name}"

STATUS =((0,"Pending"),(1,"Approved"),(2,"Declined"))               #current joining status of members
AUTH =((0,"President"),(1,"Core-Members"),(2,"Elder"),(3,"Member")) #authorities of members

class GroupMember(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE,related_name="memberships")
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name="user_groups")
    status = models.IntegerField(choices=STATUS, default=0)
    auth = models.IntegerField(choices=AUTH, default=3)
    def __str__(self):
        return self.user.username +","+ self.group.title

    class Meta:
        unique_together = ("group", "user")

Group/forms.py
from django import forms
from .models import Channel, Group
from Tag.models import Tag
official_tag=['official','avishkar','freshers']


class ChannelCreateForm(forms.ModelForm):

    class Meta:
        model = Channel
        fields = ['name']


class GroupUpdateForm(forms.ModelForm):

	class Meta:
		model = Group
		fields = ['description', 'logo']

class GroupCreateForm(forms.ModelForm):
    class Meta:
        model=Group
        fields=['title','tags','description','logo']

    def __init__(self,*args,**kwargs):
        user = kwargs.pop('user',None)
        super().__init__(*args,**kwargs)
        if not user.is_superuser:
            self.fields['tags'].queryset=Tag.objects.exclude(name__in=official_tag)

Group/views.py
from django.shortcuts import render, get_object_or_404 , redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.db import IntegrityError
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.template.loader import render_to_string
from django.http import HttpResponseRedirect, JsonResponse
from Tag.models import Tag
from .models import Group, GroupMember, Channel
from Post.models import GroupPost
from .forms import ChannelCreateForm,GroupUpdateForm,GroupCreateForm
from django.core.paginator import Paginator

#class to create group
class CreateGroup(LoginRequiredMixin, CreateView):
    model = Group
    form_class=GroupCreateForm

    def form_valid(self, form):
        form.instance.created_by = self.request.user #assigning create_by
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs=super().get_form_kwargs()
        kwargs.update({'user':self.request.user})  #adding instance of current members in **kwargs
        return kwargs

#detail view of group
@login_required
def SingleGroup(request, slug, activechannel):
    group = Group.objects.filter(slug=slug).first()
    achannel = Channel.objects.filter(parentgroup = group, name = activechannel).first()
    channelform = ChannelCreateForm(request.POST)
    if(channelform.is_valid()):                                     #if channelform is valid then assigning its group parent and saving it
        channelform.instance.parentgroup = group
        channelform.save()
        messages.success(request, f'Channel created')
        return redirect(group.get_channel_url(channelform.instance.name))
    context = {
        'gmember' : GroupMember.objects.filter(group=group).filter(status=0),#list of pending members
        'tags': Tag.objects.all,#list of tags
        'channels' : Channel.objects.filter(parentgroup = group),#list of all channels of that group
        'group' : group, #intance of group
        'activechannel' : achannel,#inctance of current channel
        'countmem': GroupMember.objects.filter(group=group).filter(status=1).order_by('auth'),#list of accepted member
        'channelform' : channelform,
        'gform' : GroupUpdateForm(instance = group)
    }
    if request.user in group.members.all() and request.user.is_authenticated:
        context['cgmember'] = get_object_or_404(GroupMember,group=group,user=request.user)#GroupMember object of current user and group
    if request.method == 'POST':
        gform = GroupUpdateForm(request.POST, request.FILES, instance = group)#form for updating group details
        if gform.is_valid():
            gform.save()
    # context['posts']
    posts = GroupPost.objects.filter(parentchannel = achannel)
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    posts = paginator.get_page(page_number)
    context['posts']=posts
    return render(request, 'Group/group_detail.html', context)

#view to show list of groups
class ListGroups(LoginRequiredMixin,ListView):
    model = Group
    paginate_by = 12
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

#method to join and leave group
@login_required
def addmember(request,slug):
    group = Group.objects.filter(slug=slug).first()
    try:
        GroupMember.objects.create(user=request.user,group=group) #GroupMember object of current user and group

    except IntegrityError:
        GroupMember.objects.get(user=request.user,group=group).delete()
        if(group.members.count()==0):                              #if all members leave then group will be disbanded
            group.delete()
            return redirect('blog-home')
        else:
            messages.warning(request,("left successfully {}".format(group.title)))

    return redirect('group-detail',slug=slug,activechannel='General')

#method to accept a member in a group
@login_required
def accept(request,userd,slug):
    group = Group.objects.filter(slug__iexact=slug).first() #getting object of group
    user = get_object_or_404(User,username=userd)
    member = GroupMember.objects.get(user=user,group=group) #GroupMember object of current user and group
    member.status = 1
    member.save()
    return redirect('group-detail',slug=slug,activechannel='General')

#method to reject an joining application
@login_required
def reject(request,userd,slug):
    group = Group.objects.filter(slug=slug).first()         #getting object of group
    user = get_object_or_404(User,username=userd)
    GroupMember.objects.get(user=user,group=group).delete() #GroupMember object of current user and group
    return redirect('group-detail',slug=slug,activechannel='General')

#method to promote and demote authority of group members
@login_required
def promote_demote(request):
    slug = request.POST.get('slug')
    userd = request.POST.get('userd')
    choice = request.POST.get('choice')
    print(slug)
    print(userd)
    group = Group.objects.filter(slug__iexact=slug).first() #getting object of group
    user = get_object_or_404(User,username=userd)           #getting instance of member
    member = GroupMember.objects.get(user=user,group=group) #getting object of GroupMember model
    if choice == '1':                                       #promoting demoting according to choice
        member.auth=member.auth-1
    else:
        member.auth=member.auth+1
    member.save()                                           #updating authority of member
    context = {
        'countmem' : GroupMember.objects.filter(group=group).filter(status=1).order_by('auth'), # all cuurent accepted members
        'group' : group,

    }
    if request.user in group.members.all() and request.user.is_authenticated:
        context['cgmember'] = get_object_or_404(GroupMember,group=group,user=request.user)  #GroupMember object of current user and group
    if request.is_ajax():
        html = render_to_string('Group/member-list.html',context, request = request)
        return JsonResponse({'form':html})
    else:
        return HttpResponse('Meme')

Group/templates/Group/add.html
{% extends "base.html" %}
{% block content %}
    <h1>addded</h1>

{% endblock %}

Group/templates/Group/ex.html
{% extends "base.html" %}
{% block content %}
    asdka
{% endblock %}

Group/templates/Group/group_detail.html
{% extends "base.html" %}
{% load static %}


{%block content%}
<!-- {% include 'snippets/circularImageStyle.html' %} -->
{% load crispy_forms_tags %}
{% load materializecss %}

<div class="row">
    <div id="leftMostColumn" class="col s12 l2">

    </div>
    <div id="centerMostColumn" class="col s12 l7">
        <div class="card">
            <div class="card-image">
                <img src="{{group.logo.url}}">
                <!-- <h1 class="card-title"></h1> -->
                <span class="card-title">
                    <h1 class="blue-grey-text text-darken-4" ;>{{group.title}}</h1>

                    <!-- <h1 class="text" style="color: #ffffff; background-color: #263238";>{{group.title}}</h1> -->
                </span>
            </div>
            <div class="card-content">
                <div class="row">
                    <div class="col s8 l8">
                        <h4>Description:</h4>
                        <p class="flow-text">{{group.description}}</p>
                    </div>
                    <div class="col s4 l4">
                        <h3>Members:{{countmem.count}}</h3>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12 l12">

                    </div>

                </div>

                {# join and leave section#}
                <div class="divider"></div>
                {% if not user in group.members.all %}
                <a href="{%url 'addmember' slug=group.slug%}" class="btn blue right">Join</a>
                {% elif user in group.members.all and cgmember.status == 0 %}
                <h3>Your application is Pending!!</h3>
                {% else %}
                <a href="{%url 'addmember' slug=group.slug%}" class="btn red right" >Leave</a>
                {% endif %}

                {% if cgmember.status == 1 %}
                {% if cgmember.auth < 2 %}
                <a class="waves-effect waves-light btn modal-trigger" href="#exampleModalCenter1">
                    Request List
                </a>
                <a class="waves-effect waves-light btn modal-trigger" href="#exampleModalCenter3">
                    Edit Group Info
                </a>
                {% endif %}


                <a class="waves-effect waves-light btn modal-trigger" href="#exampleModalCenter2">
                    Members List
                </a>

                <div class="divider"></div>
                <style media="screen">
                    .bigButton{
                        position: absolute;
                        top: 8%;
                        right:4%;
                        transform: scale(3.0);
                    }
                </style>
                <div class="bigButton"  >
                    <span class="card-title activator grey-text text-darken-4"><i class="material-icons ">more_vert</i></span>
                </div>
            </div>
            <div class="card-reveal">
                <span class="card-title grey-text tex   t-darken-4 ">Card Title<i class="material-icons right">close</i></span>
                <p>Here is some more information about this product that is only revealed once clicked on.</p>
            </div>
            <div class="card-action">
                <a href="#">This dis a link</a>
            </div>
        </div>
        <style media="screen">
            .circular--portrait {
                position: relative;
                width: auto;
                height: 40px;
                overflow: hidden;
                border-radius: 50%;
            }

            .circular--portrait img {
                width: 100%;
                height: auto;
            }

            .circular--square {
                border-radius: 50% !important;
            }

            .circular--landscape {
                /* margin: 4vh; */

                display: inline-block;
                position: relative;

                max-width: 4vh;
                max-height: 4vh;
                /* width: 200px; */
                height: 10vh;
                overflow: hidden;
                border-radius: 50%;
            }

            .circular--landscape img {

                width: auto;
                height: 100%;
                /* margin-left: -50px; */
            }

            .myCard-left {
                position: absolute;
                top: 2vh;
                left: 2vh;
            }

            .tag {
                font-size: 1.1rem;
            }
            .card{
                min-height: 30vh;
            }
            /* .tag-thin{
                font-weight: 300;
            } */
        </style>
        {% if posts %}
        {% for post in posts %}
        {% include 'snippets/postCard.html' %}
        {% endfor %}
        {% else %}
        <h1>No Posts yet</h1>
        {% endif %}
        {% endif %}

     <div class="pagination">
    <span class="step-links">
        {% if posts.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ posts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        </span>

        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">next</a>
            <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
    </div>
    <div id="rightMostColumn" class="col s12 l3">
        <div class="card">
            <div class="card-content center">
                <span class="card-title">
                    {% if user.is_authenticated and cgmember.status == 1%}
                    <h4>Channels</h4>
                </span>
                {% if cgmember %}
                {% if activechannel.name == "Announcements" and cgmember.auth > 2 %}
                {% else %}
                <a  href="{% url 'group-post-create' slug=group.slug channel=activechannel.name %}" class="btn btn-large " > Create  Post </a>
                <a href="{% url 'group-poll-create' slug=group.slug channel=activechannel.name %}"  class="btn btn-large amber   	indigo-text text-darken-4 center"> Create Poll </a>
                <h5 align="center">
                    </h5>
                <h5 align="center">    </h5>
                {% endif %}
                {% endif %}
                <ul class="collection">
                    {% for c in channels %}
                    <li class="collection-item"> <a href="{% url 'group-detail' slug=group.slug activechannel=c.name %}">
                            <p> {{c.name}} </p>
                        </a> </li>
                    {% endfor %}
                </ul>
                {% endif %}
                {% if cgmember %}
                {% if cgmember.auth < 2 %}
                <h5 align="center">  <a  href = "#channelmodal" class="waves-effect waves-light btn modal-trigger"> Add Channel </a></h5>
                {% endif %}
                {% endif %}
            </div>
        </div>

    </div>
</div>

<!-- Modal Structure -->
<div id="channelmodal" class="modal">
    <div class="modal-content">
      <form method = "post">
       {% csrf_token %}
        <h4>Channel Name</h4>
        <div class="modal-body">
          {{ channelform|crispy }}
          </div>
          <div class = "modal-footer">
            <button type="submit" class="btn btn-large">Create</button>
            </div>
        </form>
</div>
</div>


<div id="exampleModalCenter1" class="modal">
    <div class="modal-content">
        <h4>Pending List</h4>

        <div class="modal-body">
            {% for mem in gmember %}
            <div class="row">
                <div class="col s8 l8">
                    <div class="myChip chip">
                        <img src="{{  mem.user.profile.image.url }}" alt="Contact Person">
                        {% if  mem.status == 0 %}
                            @{{mem.user.username}}
                        {%endif%}
                    </div>


                </div>
                <div class="col s4 l4">
                    <a href="{% url 'accept' slug=group.slug userd=mem.user %}" class="btn green">Accept</a>
                    <a href="{% url 'reject' slug=group.slug userd=mem.user %}" class="btn red">Reject</a>
                </div>

            </div>
            {%endfor%}
        </div>
        <div class="modal-footer">

            <a href="" class="btn green">Save changes</a>
        </div>
    </div>
    <div class="modal-footer">
    </div>
</div>

<div id="exampleModalCenter2" class="modal">
    <div class="modal-content">
        <h4>Members List</h4>
        <div class="modal-body">
            <div id="memberlist">
                {% include 'Group/member-list.html' %}
            </div>
        </div>
        <div class="modal-footer">

            <a href="" class="btn btn-small green">Save changes</a>
        </div>
    </div>
    <div class="modal-footer">
    </div>
</div>
<div id="exampleModalCenter3" class="modal">
    <div class="modal-content">
        <h4>Members List</h4>
        <div class="modal-body">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
            <div class="modal-body">
                        <fieldset class="form-group">
                        {{gform|materializecss}}
                        </fieldset>
            </div>
            <div class="modal-footer">
                <a href="">
                <button type="submit" class="btn btn-outline-success md-4">Save Changes</button></a>
                </form>
        </div>
    </div>
    <div class="modal-footer">
    </div>
</div>


{%endblock%}
{% block js %}
<script type="text/javascript">
    $(document).ready(function(event) {
        $(document).on('click', '#promote', function(event) {
            event.preventDefault();


            var slug = $(this).attr('slug');
            var userd = $(this).attr('userd');
            var choice = $(this).attr('choice');


            $.ajax({
                type: 'POST',
                url: '{% url "promote_demote" %}',
                data: {
                    'slug': slug,
                    'userd': userd,
                    'choice': choice,
                    'csrfmiddlewaretoken': '{{csrf_token}}'
                },
                success: function(response) {
                    $('#memberlist').html(response['form'])
                    console.log('Success');
                    // $("#love").addClass("red-text");
                },
                error: function(rs, e) {
                    console.log(rs.responseText);
                }
            });

        });
    });
</script>
{% endblock %}
{% url 'profile' slug=user.username %}

Group/templates/Group/group_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{%block content%}
{% include 'snippets/bootstrapLibRequirements.html' %}
<div class="container">
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <h1>Group</h1>
                {{form|crispy}}
            </fieldset>
            <div class="form-group">
            <button class="btn btn-outline-info" type="submit"> Create Group </button>
            </div>
        </form>
    </div>
</div>
{%endblock%}

Group/templates/Group/member-list.html
<style media="screen">
    .circular--portrait {
        position: relative;
        width: auto;
        height: 40px;
        overflow: hidden;
        border-radius: 50%;
    }

    .circular--portrait img {
        width: 100%;
        height: auto;
    }

    .circular--square {
        border-radius: 50% !important;
    }

    .circular--landscape {
        /* margin: 4vh; */
        display: inline-block;
        position: relative;
        max-width: 10vh;
        max-height: 10vh;
        /* width: 200px; */
        height: 10vh;
        overflow: hidden;
        border-radius: 50%;
    }

    .circular--landscape img {

        width: auto;
        height: 100%;
        /* margin-left: -50px; */
    }

    /* .card{
        height: 10vh;
    } */
</style>

{% for mem in countmem %}
<!-- <li class="collection-item">

        <div class="row">
            <div class="col s4 l4">
                <div class="myChip chip">
                    <img src="{{  mem.user.profile.image.url }}" alt="Contact Person">
                    <p>@{{mem.user.username}}</p>
                    <br>
                    Designation:{{mem.get_auth_display}}
                </div>
            </div>
            {% if cgmember.auth < 2 and cgmember.auth < mem.auth %}

            <div class="col s6 l6">
                <form action="{% url 'promote_demote' %}" method="post">
                    {% csrf_token %}
                    <button name="1" id="promote" class="btn btn-small green" slug={{group.slug}} userd="{{mem.user}}" choice='1' type="submit">Promote</button>
                    {% if  mem.auth < 3 %}
                    <button name="2" id="promote" class="btn btn-small red" slug={{group.slug}} userd="{{mem.user}}" choice='0' type="submit">Demote</button>
                    {% endif %}
                    <br>

                </form>
            </div>
            <div class="col s2 l2">
                <a href="{% url 'reject' slug=group.slug userd=mem.user %}" class="btn-floating btn-small red">
                    <i class="material-icons">remove</i>
                </a>
            </div>
            {%endif%}

        </div>


    </li> -->
<!-- <div class="card">
        <div class="card-content">
            <div class="row">
                <div class="col s3">
                    <div class="circular--landscape ">
                        <img src="{{  mem.user.profile.image.url }}">
                    </div>
                </div>
            </div>
        </div>
    </div> -->
<div class="row">
    <div class="col s1">
        <div class="circular--landscape ">
            <img src="{{  mem.user.profile.image.url }}">
        </div>
    </div>
    <div class="col s2 offset-s1 valign-wrapper">
        <div class="container">
        <a href="{% url 'profile' slug=mem.user.username%}">
            <h5 class=" indigo-text text-darken-4"> @{{mem.user.username}}</h5></a>

        </div>

    </div>
    <div class="col s2 ">
        <div class="container">
            <h5 class=" indigo-text text-darken-4">&nbsp&nbsp&nbsp{{mem.get_auth_display}}</h5>

        </div>

    </div>

    <div class="col s6">
        <div class="right">
            {% if cgmember.auth < 2 and cgmember.auth < mem.auth %}

            <form action="{% url 'promote_demote' %}" method="post">
                {% csrf_token %}
                <button name="1" id="promote" class="btn btn-small green" slug={{group.slug}} userd="{{mem.user}}" choice='1' type="submit">Promote</button>
                {% if  mem.auth < 3 %}
                <button name="2" id="promote" class="btn btn-small red" slug={{group.slug}} userd="{{mem.user}}" choice='0' type="submit">Demote</button>
                {% endif %}

            </form>

            {% else %}


            <button class="btn btn-small green disabled">Promote</button>

            <button class="btn btn-small red disabled">Demote</button>



            {%endif%}
            {% if cgmember.auth < 2 and cgmember.auth < mem.auth %}
            <a href="{% url 'reject' slug=group.slug userd=mem.user %}" class="btn-floating btn-small red ">
                <i class="material-icons">remove</i>
            </a>
            {% else %}
            <a class="btn-floating btn-small red  disabled">
                <i class="material-icons">remove</i>
            </a>
            {%endif%}
        </div>
    </div>



</div>
<!--
<div class="card horizontal">
    <div class="card-image">


    </div>
    <div class="card-stacked">
        <div class="card-content">
            <p class="flow-text indigo-text text-darken-4">@{{mem.user.username}}|{{mem.get_auth_display}}

                {% if cgmember.auth < 2 and cgmember.auth < mem.auth %}
                <a href="{% url 'reject' slug=group.slug userd=mem.user %}" class="btn-floating btn-small red right">
                    <i class="material-icons">remove</i>
                </a>
                {% else %}
                <a class="btn-floating btn-small red right disabled">
                    <i class="material-icons">remove</i>
                </a>
                {%endif%}
            </p>

        </div>
        <div class="card-action">
            {% if cgmember.auth < 2 and cgmember.auth < mem.auth %}
            <div class="right">
                <form action="{% url 'promote_demote' %}" method="post">
                    {% csrf_token %}
                    <button name="1" id="promote" class="btn btn-small green" slug={{group.slug}} userd="{{mem.user}}" choice='1' type="submit">Promote</button>
                    {% if  mem.auth < 3 %}
                    <button name="2" id="promote" class="btn btn-small red" slug={{group.slug}} userd="{{mem.user}}" choice='0' type="submit">Demote</button>
                    {% endif %}

                </form>
            </div>
            {% else %}
            <div class="right">

                <button class="btn btn-small green disabled">Promote</button>

                <button class="btn btn-small red disabled">Demote</button>

            </div>

            {%endif%}
        </div>
    </div>
</div>
 -->

{% endfor %}